# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Sales-API

on:
  push:
     branches: 
       - main
       - staging
       - dev

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Build
      run: go build -o sales-api .

    - name: Test
      run: go test .

    - name: Upload Go Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: go-build
        path: sales-api

  appsec:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Build
      run: go build .

    - name: SonarQube SAST
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Trivy SCA Scan
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: 'fs'
        format: 'table'
        output: 'sbom-table.txt'
        scan-ref: '.'

    - name: Upload Trivy report
      uses: actions/upload-artifact@v4
      with:
        name: sbom-trivy-report
        path: sbom-table.txt