# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
     branches: 
       - main
#    branches: [ "main", "staging", "dev" ]
#  pull_request:
#    branches: [ "main", "staging" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Build
      run: go build .

    - name: Test
      run: go test .

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # Run the OWASP Dependency-Check Action
    - name: Run OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      id: Depcheck
      with:
        project: 'golang-api' # Name of the project
        path: '.' # Scan the whole repository workspace
        format: 'HTML,JSON' # Generate easy-to-read HTML and machine-readable JSON reports
        out: 'reports' # Output reports to a 'reports' directory

    # Upload the generated reports as an artifact
    - name: Upload OWASP Dependency-Check Report
      uses: actions/upload-artifact@v4
      with:
        name: OWASP-Dependency-Check-Report
        path: reports/ # Upload the entire reports directory       

#    - name: Upload Artifacts
#      uses: actions/upload-artifact@v3
#      with:
#        name: go-build