# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
     branches: 
       - main
#    branches: [ "main", "staging", "dev" ]
#  pull_request:
#    branches: [ "main", "staging" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Build
      run: go build .

    - name: Test
      run: go test .

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  appsec:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - uses: actions/checkout@v4

    - name: Install Trivy
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: fs 
        scan-ref: .
        format: json
        output: sbom-trivy-report.json

    - name: Upload Trivy report
      uses: actions/upload-artifact@v4
      with:
        name: sbom-trivy-report
        path: sbom-trivy-report.json

    # - name: Install and Run govulncheck
    #   run: |
    #     go install golang.org/x/vuln/cmd/govulncheck@latest
    #     export PATH=$PATH:$(go env GOPATH)/bin
    #     govulncheck ./... > sca-report.txt

    # - name: Upload report artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: sca-report
    #     path: sca-report.txt

#    - name: Upload Artifacts
#      uses: actions/upload-artifact@v3
#      with:
#        name: go-build